openapi: 3.0.3
info:
  title: WAVE 2 Project API
  version: 1.0.0
  description: Wave 2 API documentation
paths:
  /contact/:
    post:
      operationId: contact_create
      description: A simple APIView for creating contact entires.
      tags:
      - contact
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/People'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/People'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/People'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/People'
          description: ''
components:
  schemas:
    People:
      type: object
      properties:
        email:
          type: string
          format: email
        date_created:
          type: string
          format: date-time
          readOnly: true
      required:
      - date_created
      - email
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
